version: '3.4'
services:
  app:
    image: dutchandbold/laravel-docker
    container_name: join-case-local
    ports:
      - '443:443'
    volumes:
      - ./.ssl:/config/ssl
      - ./:/web:cached
    environment:
      TZ: 'Europe/Amsterdam'
      APP_ENV: 'local'
      DB_HOST: join-case-mysql-local
      NGINX_ASSETS_EXPIRE_IN: 'off'
      NGINX_LISTEN: '443 default_server'
      NGINX_SSL: 'on'
    links:
      - db
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: join-case-mysql-local
    ports:
      - "3306:3306"
    volumes:
        - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'homestead'
      MYSQL_USER: 'homestead'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'

volumes:
  mysql-data:
